### ISSUE TITLE
Nightshade: Import in FF doesn't work nested

### ISSUE THREAD

**Issue by jakob42** [vinorodrigues/bootstrap-dark#15]
I tried to implement your nightshade solution:

```
@import "/static/default.css";

html.dark {
    @import "/static/bootstrap-nightfall.min.css";
}
```
While it works in Chrome (well, I tested Edge...), Firefox throws this error in the console: (translated by me...)

> `Declaration expected, but found '@import'.  Skipping until the next declaration.`

I found [this in the MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@import):
> Imported rules must precede all other types of rules, except @charset rules; as it is not a nested statement, @import cannot be used inside conditional group at-rules.

So I suppose it isn't allowed like that?

Thanks for your work, I'll probably will use one of your other solutions, even though I liked the idea of having a bad bad switching button. :)

**Comment by vinorodrigues** [comment]
yes - the nested `@import` problem comes from SASS.  it's documented here: https://sass-lang.com/documentation/at-rules/import

>  Heads up! The Sass team discourages the continued use of the @import rule. Sass will gradually phase it out over the next few years, and eventually remove it from the language entirely. Prefer the @use rule instead.  *[..]*

This is a issue with Bootstrap core - so I can't fix it - and I don't think they can either as the `@use` requires namespacing, and BS5 wasn't built for that.   I hear rumors that this will be fixed in v6, but then again v6 will also have dark-mode.

Thanks for the thanks, and thanks for submitting the issue.

*(**Closing** - can't fix)*
