### ISSUE TITLE
How did you do your color diffs?

### ISSUE THREAD

**Issue by Carl-Hugo** [vinorodrigues/bootstrap-dark#2]
Hey! 

Excellent work that you did there, loading the core CSS, then the color override is the most optimal option indeed and I'd be curious to know how you did it and how it could be automated to port something similar to my [bootstrap-dark](https://github.com/ForEvolve/bootstrap-dark) project. 

One of my concerns was maintainability, so I don't need to spend hours over each minor release of Bootstrap.

If it is done manually, updating to new version of Bootstrap could become tedious, which is why I decided to go "all-out duplicate" in the first place. Well, that and that I did not plan initially to convert the whole thing, it was just a convenience for one of my projects (dark only), that became a few of my projects, that is now my default when I start a project with a Web GUI. The whole thing became themeable after someone asked for it, and so on.

If I could automate your "color extraction" logic, I'd be able to optimize the output of my project, making people happy (see ForEvolve/bootstrap-dark#20); which would also make sense.
Thinking about that, I could probably parse all the SCSS files, then generate a lighter copy with only the color stuff in them, but, unless I find a good SCSS parser that would allow me to do that, coding one might take time (or not; I never really think of that before).

That said, I may borrow a few ideas from you/this project in the future (I just need to find some spare time for that), like:
- A GitHub Pages deployment
- The kitchen-sink pages
- Maybe take a look at your color variables to generate more variants or improve mine (I'm not a graphical designer)

That said, I welcome contributions if you have spare time, which could lead to a unified alternative until Bootstrap officially releases dark theme support. United we are stronger 😉 

Cheers! 🍻

**Comment by vinorodrigues** [comment]
Thank so much - awesome compliment from someone whom inspired me.  I'll try to answer your many questions:

* __How I did it__ - well, to be honest, I'm nowhere near any good at UI.  I just try to follow the recommendations and emulate those I deem worthy.  So for the color combos I used Bootswatch/Darkly for the palette, except the primary - that was a derivative of my fav. color #069 ... I think I applied a `darken()` on it and just copied out the color code.  I was following a Material design principle of the Appbar **not** being the primary color, but I didn't want to loose the blue of the default theme.  The grays I borrowed from another Material paper - where I could re-find the sources I've updated the `_variables-alt.scss` with the links.  (Thanks for reminding me.)

* __automated__ - nope, I just churned the code manually, line for line.  The grays were challenging, I would see a line `$xyz: $gray-200` and change it to it's opposite `$xys-alt: $gray-800-alt` ... tested it.  Some worked, some didn't ... you'll see a few `mix($gray-600-alt, $gray-700-alt)` because I just wasn't happy with either and wanted something in-between.

* __maintainability__ - impossible for me.  I think I say so in the README.  I don't develop for a day-job, so finding the time is really challenging.  (The only reason I could churn out both Foundswatch and bootstrap-dark was because of the Covid lock down.)

* __parser__ - that will prob. be more work that the worth of its effort.  Complex things like shadows will make the code really large.  And then who's "rules" do you follow.  Google Material uses `rgba()` with various levels of transparencies to do theirs, and others use solid colors.  My thinking is that this paper convinces the authors to adopt dark mode rather sooner than later - so if that plays out all out efforts will be for naught anyway.

* __borrowing my ideas__ - hey that's what I wrote this for.  For ppl. to expand knowledge.  MIT license, so go right ahead!

* __contributions__ & __united__ - I'm humbled.  Would love to share ideas - I'll reach out to you via email.  Thank you.  Oh... and ditto your thoughts on this.
